Cta\AisheBundle\Entity\Certification:
    type: entity
    repositoryClass: Cta\AisheBundle\Entity\Repository\Certification
    table: certification
    fields:
        id:
            id: true
            type: smallint
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 64
            fixed: false
            nullable: false
    oneToMany:
        certificationRequirements:
            targetEntity: CertificationRequirement
            mappedBy: certification
