imports:
    - { resource: security.yml }

framework:
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    form:
        resources:
            - ':Form:fields.html.twig'
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ CtaAisheBundle, CtaAdminAisheBundle]
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: "%kernel.root_dir%/Resources/node_modules/uglify-js/bin/uglifyjs"
            apply_to: "\.js$"
        uglifycss:
            bin: "%kernel.root_dir%/Resources/node_modules/uglifycss/uglifycss"
            apply_to: "\.css$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# Friends Of Symfony :: User Bundle
fos_user:
    db_driver:              orm
    service:
        user_manager:       cta.fos.userbundle.usermanager
    firewall_name:          main
    user_class:             Cta\AisheBundle\Entity\User
    group:
        group_class:        Cta\AisheBundle\Entity\Group
    use_listener:           false
    use_username_form_type: false
    registration:
        form:
            type: cta_user_registration
        confirmation:
            enabled:        true
            from_email:
                address:      %app_email%
                sender_name:  %app_name% Registration
    resetting:
        email:
            from_email:
                address:      %app_email%
                sender_name:  %app_name% Reset Password

# JMS :: i18n Translation routing
jms_i18n_routing:
    default_locale: en
    locales: [nl, fr, en]
    strategy: prefix_except_default