imports:
    - { resource: config.yml }
    - { resource: parameters_staging.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      grouped
        grouped:
            type:    group
            members: [nested, swift]
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: error
        swift:
            type:       swift_mailer
            from_email: %mailer_error_from%
            to_email:   %mailer_error_to%
            subject:    "[AIFSHE][EXCEPTION][%kernel.environment%]: An Error Occurred!"
            level:      error

assetic:
    filters:
        cssrewrite: ~
        uglifyjs2: null
        uglifycss: null