security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_AUDITOR:     ROLE_USER
        ROLE_ADMIN:       ROLE_AUDITOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        resources:
            pattern:  ^/css|images|js|_wdt/
            security: false
        main:
            pattern: ^/
            form_login:
                check_path:           fos_user_security_check
                login_path:           fos_user_security_login
                provider:             fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path:  cta_aishe_report_overview
            logout:
                path: fos_user_security_logout
            anonymous:    true

    access_control:
        - { path: ^/[a-z]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z]+/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z]+/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z]+/report/import/offline, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/download, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/version, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z]+/admin/devart, role: ROLE_SUPER_ADMIN }
        - { path: ^/[a-z]+/admin, role: ROLE_ADMIN }
        - { path: ^/[a-z]+/institutions, role: ROLE_AUDITOR }
        - { path: ^/[a-z]+/institution, role: ROLE_ADMIN }
        - { path: ^/[a-z]+/page, role: ROLE_USER }
        - { path: ^/[a-z]+/reports, role: ROLE_USER }
        - { path: ^/[a-z]+/report, role: ROLE_USER }
        - { path: ^/[a-z]+/, role: IS_AUTHENTICATED_ANONYMOUSLY }
