# HOME
cta_admin_aishe_homepage:
    path:  /
    defaults: { _controller: CtaAdminAisheBundle:Default:index }

# USER
cta_admin_aishe_security_user_pending_activate:
    path:  /users/pending/activate/{action}/{id}
    defaults: { _controller: CtaAdminAisheBundle:User:activateUser }
    requirements:
        action: \w+
        id:     \d+
cta_admin_aishe_security_user_pending:
    path:  /users/pending
    defaults: { _controller: CtaAdminAisheBundle:User:pendingActivation }
cta_admin_aishe_security_user:
    path:  /users/{page}
    defaults: { _controller: CtaAdminAisheBundle:User:overview, page:1 }
cta_admin_aishe_security_user_edit:
    path:  /user/{id}
    defaults: { _controller: CtaAdminAisheBundle:User:edit, id: 0 }
    requirements:
        id:  \d+

# GROUP
cta_admin_aishe_security_group:
    path:  /devart/groups
    defaults: { _controller: CtaAdminAisheBundle:Group:overview }
cta_admin_aishe_security_group_delete:
    path:  /devart/group/delete/{id}
    defaults: { _controller: CtaAdminAisheBundle:Group:delete }
    requirements:
        id:  \d+
cta_admin_aishe_security_group_edit:
    path:  /devart/group/{id}
    defaults: { _controller: CtaAdminAisheBundle:Group:edit, id: 0 }
    requirements:
        id:  \d+

# PAGE
cta_admin_aishe_page_overview:
    path:  /pages
    defaults: { _controller: CtaAdminAisheBundle:Page:overview }
cta_admin_aishe_page_edit_translation:
    path:  /page/{lang}/{id}
    defaults: { _controller: CtaAdminAisheBundle:Page:editTranslation }
    requirements:
        id:   \d+
        lang: \w+
cta_admin_aishe_page_edit:
    path:  /page/{id}
    defaults: { _controller: CtaAdminAisheBundle:Page:edit }
    requirements:
        id:  \d+


# CRITERION
cta_admin_aishe_criterion_overview:
    path:  /criteria
    defaults: { _controller: CtaAdminAisheBundle:Criterion:overview }
cta_admin_aishe_criterion_delete:
    path:  /criterion/delete/{id}
    defaults: { _controller: CtaAdminAisheBundle:Criterion:delete }
    requirements:
        id:  \d+
cta_admin_aishe_criterion_edit:
    path:  /criterion/{id}
    defaults: { _controller: CtaAdminAisheBundle:Criterion:edit, id: 0 }
    requirements:
        id:  \d+

# CRITERION ITEM
cta_admin_aishe_criterion_item_overview:
    path:  /criterion_items/{criterionId}
    defaults: { _controller: CtaAdminAisheBundle:CriterionItem:overview }
    requirements:
        criterionId:  \d+
cta_admin_aishe_criterion_item_delete:
    path:  /criterion_item/{criterionId}/delete/{id}
    defaults: { _controller: CtaAdminAisheBundle:CriterionItem:delete }
    requirements:
        criterionId:  \d+
        id:           \d+
cta_admin_aishe_criterion_item_edit_translation:
    path:  /criterion_item/{lang}/{criterionId}/{criterionItemId}
    defaults: { _controller: CtaAdminAisheBundle:CriterionItem:editTranslation }
    requirements:
        lang:             \w+
        criterionId:      \d+
        criterionItemId:  \d+
cta_admin_aishe_criterion_item_edit:
    path:  /criterion_item/{criterionId}/{id}
    defaults: { _controller: CtaAdminAisheBundle:CriterionItem:edit, id: 1 }
    requirements:
        criterionId:  \d+
        id:           \d+

# OFFLINE TOOL
cta_admin_aishe_offline_tool_overview:
    path:  /offlinetool/overview/{page}
    defaults: { _controller: CtaAdminAisheBundle:OfflineTool:overview , page: 1 }
cta_admin_aishe_offline_tool_update:
    path:  /offlinetool/update
    defaults: { _controller: CtaAdminAisheBundle:OfflineTool:update }
cta_admin_aishe_offline_tool_download:
    path:  /offlinetool/download/{id}
    defaults: { _controller: CtaAdminAisheBundle:OfflineTool:download, id:-}
    requirements:
        id:  \d+
cta_admin_aishe_offline_tool_edit:
    path:  /offlinetool/edit/{id}
    defaults: { _controller: CtaAdminAisheBundle:OfflineTool:edit, id:-}
    requirements:
        id:  \d+
cta_admin_aishe_offline_tool_remove:
    path:  /offlinetool/remove/{id}
    defaults: { _controller: CtaAdminAisheBundle:OfflineTool:remove, id:-}
    requirements:
        id:  \d+
cta_admin_aishe_offline_tool_outdated:
    path: /offlinetool/outdated
    defaults: { _controller: CtaAdminAisheBundle:OfflineTool:outdated }