<?php

namespace Cta\AisheBundle\Entity\Repository;

/**
 * Base
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Base extends \Devart\CommonBundle\Entity\Repository\Base
{
}
