<?php

namespace Cta\AisheBundle\Entity\Repository;

use Devart\CommonBundle\Entity\Repository\Base;
use Doctrine\ORM\Query;

/**
 * CriterionItem
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Chart extends Base
{

}
