<?php

namespace Cta\AisheBundle\Entity\Repository;

use Devart\CommonBundle\Entity\Repository\Base;

/**
 * CriterionItemTranslation
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriterionItemTranslation extends Base
{
}
