<?php

namespace Cta\AisheBundle\Entity\Repository;

use Devart\CommonBundle\Entity\Repository\Base;

/**
 * Institution
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Institution extends Base
{
    /**
     * @param array $params
     * @return array
     */
    public function findOverview(array $params = array())
    {
        $result = array(
            'items' => array(),
            'count' => 0,
        );

        $qb = $this->getEntityManager()->createQueryBuilder();

        $query = $qb->select('i', 'user_cr', 'user_mo')
            ->from('CtaAisheBundle:Institution' , 'i')
            ->leftJoin('i.createdBy'            , 'user_cr')
            ->leftJoin('i.modifiedBy'           , 'user_mo')
            ->andWhere('i.status = :status')
            ->setParameter('status', \Cta\AisheBundle\Entity\Institution::ST_ACTIVE)
            ->addOrderBy('i.name', 'ASC');

        $result['count'] = $this->count($query, 'i.id');

        if (array_key_exists('start', $params)) {
            $query->setFirstResult($params['start']);
        }

        if (array_key_exists('limit', $params)) {
            $query->setMaxResults($params['limit']);
        }

        $result['items'] = $query->getQuery()->getArrayResult();

        return $result;
    }
}
