<?php

namespace Cta\AisheBundle\Entity\Repository;

use Devart\CommonBundle\Entity\Repository\Base;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\EntityNotFoundException;
use Doctrine\ORM\ORMInvalidArgumentException;
use Doctrine\ORM\Query;

/**
 * Report
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Report extends Base
{
    /**
     * @param array $params
     * @return array
     */
    public function findOverview(array $params = array())
    {
        $result = array(
            'items' => array(),
            'count' => 0,
        );

        $qb = $this->getEntityManager()->createQueryBuilder();

        $query = $qb->select('r', 'user_cr', 'user_mo')
            ->from('CtaAisheBundle:Report'  , 'r')
            ->leftJoin('r.createdBy'        , 'user_cr')
            ->leftJoin('r.modifiedBy'       , 'user_mo')
            ->andWhere('r.status != :status')
            ->setParameter('status', \Cta\AisheBundle\Entity\Report::ST_DELETED)
            ->orderBy('r.createdAt', 'DESC');

        $onlyShowOfficial = true;

        if (array_key_exists('user', $params)) {
            if (array_key_exists('isAuditor', $params) && $params['isAuditor']) {
                $query->andWhere('r.createdBy = :creator OR r.institution = :institution');
                $query->setParameter('institution', $params['user']->getInstitution());
            } else {
                $onlyShowOfficial = false;
                $query->addSelect('users');
                $query->leftJoin('r.users', 'users');
                $query->andWhere('r.createdBy = :creator OR users = :creator');
            }
            $query->setParameter('creator', $params['user']);
        }

        if ($onlyShowOfficial) {
            $query->andWhere('r.isOfficial = 1');
        }

        $result['count'] = $this->count($query, 'r.id');

        if (array_key_exists('start', $params)) {
            $query->setFirstResult($params['start']);
        }

        if (array_key_exists('limit', $params)) {
            $query->setMaxResults($params['limit']);
        }

        $result['items'] = $query->getQuery()->getArrayResult();
        return $result;
    }

    /**
     * @param $id
     * @return mixed
     */
    public function findNotDeletedById($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $query = $qb->select('r')
            ->from('CtaAisheBundle:Report', 'r')
            ->andWhere('r.id = :id')
            ->andWhere('r.status != :status')
            ->setParameter('id', $id)
            ->setParameter('status', \Cta\AisheBundle\Entity\Report::ST_DELETED)
            ->getQuery();

        try {
            return $query->getSingleResult();
        } catch (NoResultException $e) {
            return null;
        }
    }

    /**
     * @param $id
     * @param $lang
     * @return mixed|null
     * @throws \Doctrine\ORM\ORMInvalidArgumentException
     */
    public function findForShow($id, $lang)
    {
        if (!is_int($lang) || $lang < 1) {
            throw new ORMInvalidArgumentException('wrong parameters inserted.');
        }

        $qb = $this->getEntityManager()->createQueryBuilder();

        $query = $qb->select('r', 'ri', 'ci', 'c', 'crby', 'i', 'users')
            ->from('CtaAisheBundle:Report',         'r')
            ->leftJoin('r.reportItems',             'ri', Query\Expr\Join::WITH, $qb->expr()->eq('ri.status', \Cta\AisheBundle\Entity\ReportItem::ST_ACTIVE))
            ->leftJoin('ri.criterionItem',          'ci', Query\Expr\Join::WITH, $qb->expr()->eq('ci.status', \Cta\AisheBundle\Entity\CriterionItem::ST_ACTIVE))
            ->leftJoin('ci.criterion',              'c', Query\Expr\Join::WITH, $qb->expr()->eq('c.status', \Cta\AisheBundle\Entity\Criterion::ST_ACTIVE))
            ->leftJoin('r.institution',             'i', Query\Expr\Join::WITH, $qb->expr()->eq('i.status', \Cta\AisheBundle\Entity\Institution::ST_ACTIVE))
            ->leftJoin('r.users',                   'users')
            ->leftJoin('r.createdBy',               'crby')
            ->andWhere('r.id = :id')
            ->andWhere('r.status != :status')
            ->setParameter('status', \Cta\AisheBundle\Entity\Report::ST_DELETED)
            ->setParameter('id', $id)
            ->getQuery();

        try {
            return $query->getSingleResult(Query::HYDRATE_ARRAY);
        } catch (NoResultException $e) {
            return null;
        }
    }

    /**
     * @param $id
     * @throws \Doctrine\ORM\EntityNotFoundException
     */
    public function delete($id)
    {
        $em = $this->getEntityManager();

        $report = $em->getRepository('CtaAisheBundle:Report')->find($id);
        if (!$report) {
            throw new EntityNotFoundException('Entity with id [' . $id . '] could not be found.');
        }

        // flag reportItems as deleted
        foreach ($report->getReportItems() as $reportItem) {
            $reportItem->setStatus(\Cta\AisheBundle\Entity\Report::ST_DELETED);
        }

        // flag chart settings as deleted
        $report->getChartSettings()->setStatus(\Cta\AisheBundle\Entity\Chart::ST_DELETED);

        // flag report as deleted
        $report->setStatus(\Cta\AisheBundle\Entity\Report::ST_DELETED);

        // save changes
        $em->flush();
    }
}
